---
haproxy_frontend_port: 80
haproxy_balance: roundrobin
haproxy_app_backends:
  - { name: app1, host: 192.168.56.201, port: 80 }
  - { name: app2, host: 192.168.56.202, port: 80 }

common_firewalld_services:
  - http
...
