---
- name: Web servers
  hosts: web
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/secrets.yaml"
  roles:
    - role: common
      vars:
        #common_do_bootstrap: true
        #common_do_baseline: false
      tags: [common]

    - role: web
      tags: [web]
...

