$ANSIBLE_VAULT;1.1;AES256
31346433356539356664623038336237386439373737616164616265376537633932356664393263
6461363433326662353463383239373065646338633036620a373433353831343638626237623961
39653939373566636135623032306166663833333238613439316164343339303264636662646537
3439636664626433300a623161353063316266613765303561313832396564386232326165653264
63663966366239303833393535663937316139646630346230323933386630346564636462346462
62336633356262653363636131643136376233393132616537623763613434353163636239313733
30663734666633633966313332633563313061356365333932613533613965383139343535613738
63383435366463333363336537646462333832326234323134303831633438373638666539326139
35343462366263386165613239393330343030353632326239353337313133363833303365373564
63643237646332303130663061363634616561666339633365356639616662326234363165666466
31633532653939386132363761366338653063376461663530323661663633306536313863333163
39396531613035373231393863633463326133336636343335353663326138613866663430313162
30613637666337343963363933666462323339613837633364376636383563616161636138373933
64626166326163396338353461633635636366313462303763366462653061353536653465393933
64363863646539653238323438346664326562646363383338633661623566616466393833663063
33313864636561386434623261343661613664373933383362623434396336623365393764333166
35363462323234383738333965373563646335633561346266333334653930376236353164376237
36323666323264333937356466633938393062643965356338663564663939313830653931663336
38313261613430646535613764663563663539343066306664313633663665663731326566323134
65353232326638653933646262393465656138316535363562323162353264333065326132383236
62656364396366393839613237363634303333643338613035306562383434633339636636373563
66316233326162346263316166383231663165666530646432313935656535303035336539346631
33616534303766643830633832326564386466353839663261633238393161656135616630336333
32326664343235643835
