$ANSIBLE_VAULT;1.1;AES256
62383933633736653061326361326265303935653136633338343035323563366332363265363630
3233393338386236636636343834303334306234653864360a363933653634653062653038643535
37356665363261636636343633313338336435626635333362313436303433386130323566333766
3133633839323265610a666630633830626631316461363265343039636339373634346439336237
39666261653765333132316565646663626538316235343536383037316662613761343862313835
64346535336630666434333534626530343133353535393030653933343636646534336335396535
37303439356633303839396261306333383435336133323163333531333434383433353863653065
38313536356563366436643033633831303838616166613164333131643436633632383164383939
66333330616435653938383166343562373633633761313062633462383038633637
